"""One-shot SQLite → PostgreSQL data migration.

Usage:
    python scripts/migrate_to_postgres.py --source ./data/jira_analytics.db --target postgresql://app:PASS@host:5432/jira_analytics_prod

Strategy:
- Iterates Base.metadata.sorted_tables (FK-dependency order).
- Copies all rows for each table from SQLite into Postgres using
  parameterized inserts in batches.
- Skips DEFAULT_SKIP (caches, sync history) — these regenerate themselves.
- Pre-flight: target schema must already be at alembic HEAD; target tables
  must be empty unless --force is set (then they are truncated first).
- Post-pass: prints per-table row counts and flags any mismatches.

Designed to be run by the sysadmin on the new server, after the empty
Postgres has alembic upgrade head applied (see deploy/SYSADMIN.md and
docs/superpowers/specs/2026-05-16-server-deployment-design.md §7).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import List, Set

# Allow running directly from the project root: `python scripts/migrate_to_postgres.py ...`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import (
    Table,
    create_engine,
    delete,
    func,
    inspect,
    select,
)
from sqlalchemy.engine import Engine, make_url

# Ensure all models register with Base.metadata
os.environ.setdefault("JWT_SECRET_KEY", "migration-script")  # bypass validator

from app.database import Base  # noqa: E402
import app.models  # noqa: E402,F401


# These never need to be copied — they are caches or runtime state that
# rebuild themselves on the new server.
DEFAULT_SKIP: Set[str] = {
    "sync_state",                       # sync starts fresh on the new server
    "sync_run",                         # historical sync runs irrelevant after cutover
    "confluence_page_cache",            # rebuilds on demand
    "executive_dashboard_snapshots",    # regenerated by /executive endpoint
}


def _self_referencing_fk_columns(table: Table) -> list[str]:
    columns: list[str] = []
    for constraint in table.foreign_key_constraints:
        for element in constraint.elements:
            if element.column.table.name == table.name:
                columns.append(element.parent.name)
    return columns


def _order_rows_for_self_referencing_table(table_name: str, rows: List[dict]) -> List[dict]:
    table = Base.metadata.tables.get(table_name)
    if table is None or len(rows) < 2:
        return rows

    self_fk_columns = _self_referencing_fk_columns(table)
    if not self_fk_columns:
        return rows

    rows_by_id = {
        row["id"]: row
        for row in rows
        if row.get("id") is not None
    }
    state: dict[str, int] = {}
    ordered: list[dict] = []

    def visit(row: dict) -> None:
        row_id = row.get("id")
        if row_id is None:
            ordered.append(row)
            return

        current_state = state.get(row_id, 0)
        if current_state == 2:
            return
        if current_state == 1:
            return

        state[row_id] = 1
        for column in self_fk_columns:
            parent_id = row.get(column)
            parent_row = rows_by_id.get(parent_id)
            if parent_row is not None and parent_row is not row:
                visit(parent_row)
        state[row_id] = 2
        ordered.append(row)

    for row in rows:
        visit(row)

    return ordered


def _check_alembic_head(target_url: str) -> None:
    """Fail fast if the target schema is not at the latest revision."""
    from alembic.config import Config
    from alembic.runtime.migration import MigrationContext
    from alembic.script import ScriptDirectory

    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", target_url)
    script = ScriptDirectory.from_config(cfg)
    head = script.get_current_head()

    eng = create_engine(target_url)
    try:
        with eng.connect() as conn:
            ctx = MigrationContext.configure(conn)
            current = ctx.get_current_revision()
    finally:
        eng.dispose()

    if current != head:
        raise SystemExit(
            f"Target schema at revision {current!r}, expected HEAD {head!r}.\n"
            f"Run `alembic upgrade head` against the target before migrating."
        )


def _count_rows(engine: Engine, table: Table) -> int:
    with engine.connect() as conn:
        return int(conn.scalar(select(func.count()).select_from(table)) or 0)


def _copy_table(
    source: Engine,
    target: Engine,
    table: Table,
    batch_size: int,
) -> tuple[int, int]:
    """Copy all rows from source to target. Returns (source_count, copied)."""
    source_count = _count_rows(source, table)
    if source_count == 0:
        return 0, 0

    copied = 0
    self_fk_columns = _self_referencing_fk_columns(table)
    with source.connect() as src_conn:
        result = src_conn.execution_options(stream_results=True).execute(
            select(table)
        )
        if self_fk_columns:
            rows = [dict(row._mapping) for row in result]
            ordered_rows = _order_rows_for_self_referencing_table(table.name, rows)
            for start in range(0, len(ordered_rows), batch_size):
                batch = ordered_rows[start:start + batch_size]
                _insert_batch(target, table, batch)
                copied += len(batch)
            return source_count, copied

        batch: list[dict] = []
        for row in result:
            batch.append(dict(row._mapping))
            if len(batch) >= batch_size:
                _insert_batch(target, table, batch)
                copied += len(batch)
                batch = []
        if batch:
            _insert_batch(target, table, batch)
            copied += len(batch)
    return source_count, copied


def _insert_batch(target: Engine, table: Table, rows: List[dict]) -> None:
    with target.begin() as conn:
        conn.execute(table.insert(), rows)


def _resolve_tables(only: Set[str], skip: Set[str]) -> List[Table]:
    if only:
        chosen = [t for t in Base.metadata.sorted_tables if t.name in only]
        missing = only - {t.name for t in chosen}
        if missing:
            raise SystemExit(f"Unknown tables in --only: {sorted(missing)}")
        return chosen
    return [t for t in Base.metadata.sorted_tables if t.name not in skip]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Copy structure + data from a local SQLite snapshot into Postgres.",
    )
    parser.add_argument("--source", required=True,
                        help="SQLite file path (e.g. ./data/jira_analytics.db)")
    parser.add_argument("--target", required=True,
                        help="Postgres URL (postgresql://user:pw@host:5432/db)")
    parser.add_argument("--skip", default="",
                        help="Extra comma-separated tables to skip (added to defaults)")
    parser.add_argument("--no-default-skip", action="store_true",
                        help="Do NOT apply DEFAULT_SKIP — copy everything except --skip")
    parser.add_argument("--only", default="",
                        help="Copy only these tables (comma-separated). Overrides --skip.")
    parser.add_argument("--batch-size", type=int, default=1000)
    parser.add_argument("--dry-run", action="store_true",
                        help="Report row counts without inserting")
    parser.add_argument("--force", action="store_true",
                        help="Truncate target tables before copy (otherwise refuses non-empty)")
    args = parser.parse_args()

    if not os.path.exists(args.source):
        print(f"ERROR: source SQLite file not found: {args.source}", file=sys.stderr)
        return 1

    src_url = f"sqlite:///{args.source}"
    if make_url(args.target).get_backend_name() != "postgresql":
        print("ERROR: --target must be a postgresql:// URL", file=sys.stderr)
        return 1

    src_engine = create_engine(src_url)
    tgt_engine = None if args.dry_run else create_engine(args.target)

    try:
        print(f"Source: {src_url}")
        print(f"Target: {args.target}")
        print()

        # --- Pre-flight ---
        if not args.dry_run:
            print("[pre-flight] alembic revision on target...")
            _check_alembic_head(args.target)
            print("[pre-flight] OK\n")

        # --- Build table list ---
        only = {t.strip() for t in args.only.split(",") if t.strip()}
        extra_skip = {t.strip() for t in args.skip.split(",") if t.strip()}
        skip = set() if args.no_default_skip else set(DEFAULT_SKIP)
        skip |= extra_skip
        tables = _resolve_tables(only, skip)

        # Filter to tables that actually exist in source
        src_existing = set(inspect(src_engine).get_table_names())
        missing_in_source = [t.name for t in tables if t.name not in src_existing]
        if missing_in_source:
            print(f"[info] skipping {len(missing_in_source)} tables absent in source: "
                  f"{', '.join(missing_in_source)}\n")
            tables = [t for t in tables if t.name in src_existing]

        print(f"Will process {len(tables)} table(s). Skipping {len(skip)} by default:")
        for name in sorted(skip):
            print(f"  - {name}")
        print()

        # --- Dry run? ---
        if args.dry_run:
            print("DRY RUN — counting source rows only\n")
            total = 0
            for t in tables:
                n = _count_rows(src_engine, t)
                total += n
                print(f"  {t.name:<48} {n:>10}")
            print(f"\n  {'TOTAL':<48} {total:>10}")
            return 0

        # --- Target empty? ---
        if args.force:
            print("[force] truncating target tables in reverse FK order...")
            with tgt_engine.begin() as conn:
                for t in reversed(tables):
                    conn.execute(delete(t))
            print("[force] done\n")
        else:
            print("[check] target tables must be empty (use --force to truncate)...")
            nonempty = []
            for t in tables:
                n = _count_rows(tgt_engine, t)
                if n > 0:
                    nonempty.append((t.name, n))
            if nonempty:
                print("ERROR: target tables not empty:", file=sys.stderr)
                for name, n in nonempty:
                    print(f"  {name}: {n}", file=sys.stderr)
                print("\nRun with --force to truncate them first.", file=sys.stderr)
                return 1
            print("[check] OK\n")

        # --- Copy ---
        print("Copying...\n")
        summary: list[tuple[str, int, int]] = []
        for t in tables:
            try:
                src_count, copied = _copy_table(src_engine, tgt_engine, t, args.batch_size)
            except Exception as exc:
                print(f"  {t.name}: FAILED — {exc}", file=sys.stderr)
                summary.append((t.name, -1, -1))
                continue
            tag = "ok" if src_count == copied else "MISMATCH"
            print(f"  {t.name:<48} {src_count:>10} -> {copied:>10}  [{tag}]")
            summary.append((t.name, src_count, copied))

        # --- Final summary ---
        print("\nSummary:")
        print(f"  {'Table':<48} {'Source':>10} {'Copied':>10}")
        total_src = total_cp = 0
        problems = 0
        for name, src, cp in summary:
            flag = ""
            if src == -1:
                flag = "  FAIL"
                problems += 1
            elif src != cp:
                flag = "  MISMATCH"
                problems += 1
            else:
                total_src += src
                total_cp += cp
            print(f"  {name:<48} {src:>10} {cp:>10}{flag}")
        print(f"  {'TOTAL':<48} {total_src:>10} {total_cp:>10}")

        return 2 if problems else 0
    finally:
        src_engine.dispose()
        if tgt_engine is not None:
            tgt_engine.dispose()


if __name__ == "__main__":
    sys.exit(main())
